AWSTemplateFormatVersion: "2010-09-09"
Description: "MySQL database for app-evently"

Parameters:
    ProjectName:
        Type: String
        Default: app-evently
    Environment:
        Type: String
        Default: dev

Resources:
    ECSExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: ecs-tasks.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            Policies:
                - PolicyName: ECRAccess
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - ecr:GetAuthorizationToken
                                - ecr:BatchCheckLayerAvailability
                                - ecr:GetDownloadUrlForLayer
                                - ecr:BatchGetImage
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: "*"

    MySQLTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Sub ${ProjectName}-${Environment}-mysql
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            Cpu: 256
            Memory: 512
            ExecutionRoleArn: !Ref ECSExecutionRole
            ContainerDefinitions:
                - Name: mysql
                  Image: public.ecr.aws/docker/library/mysql:8.0
                  Essential: true
                  PortMappings:
                      - ContainerPort: 3306
                  Environment:
                      - Name: MYSQL_ROOT_PASSWORD
                        Value: root
                      - Name: MYSQL_DATABASE
                        Value: db_app_evently
                      - Name: MYSQL_ROOT_HOST
                        Value: "%"
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref CloudWatchLogGroup
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: mysql

    MySQLServiceDiscovery:
        Type: AWS::ServiceDiscovery::Service
        Properties:
            Name: mysql
            DnsConfig:
                NamespaceId:
                    Fn::ImportValue: !Sub ${ProjectName}-${Environment}-namespace-id
                DnsRecords:
                    - Type: A
                      TTL: 60
            HealthCheckCustomConfig:
                FailureThreshold: 1

    MySQLService:
        Type: AWS::ECS::Service
        Properties:
            ServiceName: mysql
            Cluster:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-cluster-name
            TaskDefinition: !Ref MySQLTaskDefinition
            DesiredCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: DISABLED
                    Subnets:
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-private-subnet-1
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-private-subnet-2
                    SecurityGroups:
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-database-sg-id
            ServiceRegistries:
                - RegistryArn: !GetAtt MySQLServiceDiscovery.Arn

    CloudWatchLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /ecs/${ProjectName}-${Environment}-mysql
            RetentionInDays: 30

Outputs:
    MySQLHost:
        Description: MySQL Hostname
        Value: !Sub mysql.${ProjectName}.local
        Export:
            Name: !Sub ${ProjectName}-${Environment}-mysql-host
