AWSTemplateFormatVersion: "2010-09-09"
Description: "Frontend web application for app-evently"

Parameters:
    ProjectName:
        Type: String
        Default: app-evently
    Environment:
        Type: String
        Default: dev
    WebImage:
        Type: String
        Default: web-app-evently
    WebTag:
        Type: String
        Default: 0.0.1
    DomainName:
        Type: String
        Default: usmp.identity.pe
    BackendURL:
        Type: String
        Default: https://api.usmp.identity.pe

Resources:
    WebSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Web Frontend
            VpcId:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-vpc-id
            SecurityGroupEgress:
                - IpProtocol: -1
                  CidrIp: 0.0.0.0/0

    WebALBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Web ALB
            VpcId:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-vpc-id
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 10.0.0.0/16

    WebSecurityGroupALBIngress:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref WebSecurityGroup
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            SourceSecurityGroupId: !Ref WebALBSecurityGroup

    Certificate:
        Type: AWS::CertificateManager::Certificate
        Properties:
            DomainName: !Ref DomainName
            ValidationMethod: DNS
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-web-certificate

    WebALB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Sub ${ProjectName}-${Environment}-web-alb
            Scheme: internet-facing
            Type: application
            Subnets:
                - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-public-subnet-1
                - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-public-subnet-2
            SecurityGroups:
                - !Ref WebALBSecurityGroup

    WebTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${ProjectName}-${Environment}-web-tg
            Port: 80
            Protocol: HTTP
            VpcId:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-vpc-id
            TargetType: ip
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckPort: traffic-port
            HealthCheckIntervalSeconds: 30
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 2
            UnhealthyThresholdCount: 2
            Matcher:
                HttpCode: 200

    WebHTTPSListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref WebALB
            Port: 443
            Protocol: HTTPS
            Certificates:
                - CertificateArn: !Ref Certificate
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref WebTargetGroup

    WebHTTPListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref WebALB
            Port: 80
            Protocol: HTTP
            DefaultActions:
                - Type: redirect
                  RedirectConfig:
                      Protocol: HTTPS
                      Port: 443
                      StatusCode: HTTP_301

    ECSExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: ecs-tasks.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            Policies:
                - PolicyName: ECRAccess
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - ecr:GetAuthorizationToken
                                - ecr:BatchCheckLayerAvailability
                                - ecr:GetDownloadUrlForLayer
                                - ecr:BatchGetImage
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: "*"

    ECSTaskRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: ecs-tasks.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: ECSAccess
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - ecs:DescribeClusters
                            Resource: "*"

    WebTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Sub ${ProjectName}-${Environment}-web
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            Cpu: 256
            Memory: 512
            ExecutionRoleArn: !Ref ECSExecutionRole
            TaskRoleArn: !Ref ECSTaskRole
            ContainerDefinitions:
                - Name: web
                  Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${WebImage}:${WebTag}
                  Essential: true
                  PortMappings:
                      - ContainerPort: 80
                  Environment:
                      - Name: VITE_API_BASE_URL
                        Value: !Sub ${BackendURL}/api
                      - Name: VITE_WS_HOST
                        Value: !Ref BackendURL
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref CloudWatchLogGroup
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: web

    WebService:
        Type: AWS::ECS::Service
        Properties:
            ServiceName: web
            Cluster:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-cluster-name
            TaskDefinition: !Ref WebTaskDefinition
            DesiredCount: 2
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: DISABLED
                    Subnets:
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-private-subnet-1
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-private-subnet-2
                    SecurityGroups:
                        - !Ref WebSecurityGroup
            LoadBalancers:
                - ContainerName: web
                  ContainerPort: 80
                  TargetGroupArn: !Ref WebTargetGroup
            HealthCheckGracePeriodSeconds: 60

    CloudWatchLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /ecs/${ProjectName}-${Environment}-frontend
            RetentionInDays: 30

    WebDNSRecord:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneName: identity.pe.
            Name: !Ref DomainName
            Type: A
            AliasTarget:
                DNSName: !GetAtt WebALB.DNSName
                HostedZoneId: !GetAtt WebALB.CanonicalHostedZoneID

Outputs:
    WebURL:
        Description: Web Application URL
        Value: !Sub https://${DomainName}
        Export:
            Name: !Sub ${ProjectName}-${Environment}-web-url

    WebALBDNS:
        Description: Web ALB DNS Name
        Value: !GetAtt WebALB.DNSName
        Export:
            Name: !Sub ${ProjectName}-${Environment}-web-alb-dns
