AWSTemplateFormatVersion: "2010-09-09"
Description: "Frontend web application for app-evently"

Parameters:
    ProjectName:
        Type: String
        Default: app-evently
    Environment:
        Type: String
        Default: dev
    WebImage:
        Type: String
        Default: web-app-evently
    WebTag:
        Type: String
        Default: 0.0.1

Resources:
    WebSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Web Frontend
            VpcId:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-vpc-id
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0

    ALB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Sub ${ProjectName}-${Environment}-alb
            Scheme: internet-facing
            Type: application
            Subnets:
                - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-public-subnet-1
                - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-public-subnet-2
            SecurityGroups:
                - !Ref WebSecurityGroup

    WebTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${ProjectName}-${Environment}-web-tg
            Port: 80
            Protocol: HTTP
            VpcId:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-vpc-id
            TargetType: ip
            HealthCheckPath: /
            HealthCheckIntervalSeconds: 30
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 2
            UnhealthyThresholdCount: 2

    WebListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref ALB
            Port: 80
            Protocol: HTTP
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref WebTargetGroup

    ECSExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: ecs-tasks.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

    ECSTaskRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: ecs-tasks.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

    WebTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Sub ${ProjectName}-${Environment}-web
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            Cpu: 256
            Memory: 512
            ExecutionRoleArn: !Ref ECSExecutionRole
            TaskRoleArn: !Ref ECSTaskRole
            ContainerDefinitions:
                - Name: web
                  Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${WebImage}:${WebTag}
                  Essential: true
                  PortMappings:
                      - ContainerPort: 80
                  Environment:
                      - Name: VITE_API_BASE_URL
                        Value: http://http-app-evently:3001/api
                      - Name: VITE_WS_HOST
                        Value: http://http-app-evently:3001
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref CloudWatchLogGroup
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: web

    WebService:
        Type: AWS::ECS::Service
        DependsOn:
            - BackendService
            - ALB
        Properties:
            ServiceName: web
            Cluster:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-cluster-name
            TaskDefinition: !Ref WebTaskDefinition
            DesiredCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
                    Subnets:
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-private-subnet-1
                        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-private-subnet-2
                    SecurityGroups:
                        - !Ref WebSecurityGroup
            LoadBalancers:
                - ContainerName: web
                  ContainerPort: 80
                  TargetGroupArn: !Ref WebTargetGroup

    CloudWatchLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /ecs/${ProjectName}-${Environment}-frontend
            RetentionInDays: 30

    BackendService:
        Type: AWS::ECS::Service
        Properties:
            ServiceName: backend
            Cluster:
                Fn::ImportValue: !Sub ${ProjectName}-${Environment}-cluster-name

Outputs:
    WebURL:
        Description: Web Application URL
        Value: !GetAtt ALB.DNSName
        Export:
            Name: !Sub ${ProjectName}-${Environment}-web-url
