AWSTemplateFormatVersion: "2010-09-09"
Description: "Network stack for app-evently"

Parameters:
    ProjectName:
        Type: String
        Default: app-evently
    Environment:
        Type: String
        Default: dev

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
            EnableDnsSupport: true
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-vpc

    PublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.0.1.0/24
            AvailabilityZone: !Select [0, !GetAZs ""]
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-public-subnet-1

    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.0.2.0/24
            AvailabilityZone: !Select [1, !GetAZs ""]
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-public-subnet-2

    PrivateSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.0.3.0/24
            AvailabilityZone: !Select [0, !GetAZs ""]
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-private-subnet-1

    PrivateSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.0.4.0/24
            AvailabilityZone: !Select [1, !GetAZs ""]
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-private-subnet-2

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-igw

    AttachGateway:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref VPC
            InternetGatewayId: !Ref InternetGateway

    EIP1:
        Type: AWS::EC2::EIP
        Properties:
            Domain: vpc
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-eip-1

    EIP2:
        Type: AWS::EC2::EIP
        Properties:
            Domain: vpc
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-eip-2

    NATGateway1:
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !GetAtt EIP1.AllocationId
            SubnetId: !Ref PublicSubnet1
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-nat-1

    NATGateway2:
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !GetAtt EIP2.AllocationId
            SubnetId: !Ref PublicSubnet2
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-nat-2

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-public-rt

    PublicRoute:
        Type: AWS::EC2::Route
        DependsOn: AttachGateway
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    PublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PublicSubnet1
            RouteTableId: !Ref PublicRouteTable

    PublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PublicSubnet2
            RouteTableId: !Ref PublicRouteTable

    PrivateRouteTable1:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-private-rt-1

    PrivateRouteTable2:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-private-rt-2

    PrivateRoute1:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref PrivateRouteTable1
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NATGateway1

    PrivateRoute2:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref PrivateRouteTable2
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NATGateway2

    PrivateSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PrivateSubnet1
            RouteTableId: !Ref PrivateRouteTable1

    PrivateSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PrivateSubnet2
            RouteTableId: !Ref PrivateRouteTable2

    # Security Groups Base
    BackendSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Backend services
            VpcId: !Ref VPC
            SecurityGroupEgress:
                - IpProtocol: -1
                  CidrIp: 0.0.0.0/0

    DatabaseSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Databases
            VpcId: !Ref VPC
            SecurityGroupEgress:
                - IpProtocol: -1
                  CidrIp: 0.0.0.0/0

    CacheSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Cache services
            VpcId: !Ref VPC
            SecurityGroupEgress:
                - IpProtocol: -1
                  CidrIp: 0.0.0.0/0

    # Security Group Rules
    DatabaseToBackendIngress:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref DatabaseSecurityGroup
            IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306
            SourceSecurityGroupId: !Ref BackendSecurityGroup

    CacheToBackendIngress:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref CacheSecurityGroup
            IpProtocol: tcp
            FromPort: 6379
            ToPort: 6379
            SourceSecurityGroupId: !Ref BackendSecurityGroup

    ECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: !Sub ${ProjectName}-${Environment}-cluster
            CapacityProviders:
                - FARGATE
            DefaultCapacityProviderStrategy:
                - CapacityProvider: FARGATE
                  Weight: 1
            Tags:
                - Key: Name
                  Value: !Sub ${ProjectName}-${Environment}-cluster

    PrivateNamespace:
        Type: AWS::ServiceDiscovery::PrivateDnsNamespace
        Properties:
            Name: !Sub ${ProjectName}.local
            Vpc: !Ref VPC
            Description: !Sub Service discovery namespace for ${ProjectName}

Outputs:
    VpcId:
        Description: VPC ID
        Value: !Ref VPC
        Export:
            Name: !Sub ${ProjectName}-${Environment}-vpc-id

    PublicSubnet1:
        Description: Public Subnet 1
        Value: !Ref PublicSubnet1
        Export:
            Name: !Sub ${ProjectName}-${Environment}-public-subnet-1

    PublicSubnet2:
        Description: Public Subnet 2
        Value: !Ref PublicSubnet2
        Export:
            Name: !Sub ${ProjectName}-${Environment}-public-subnet-2

    PrivateSubnet1:
        Description: Private Subnet 1
        Value: !Ref PrivateSubnet1
        Export:
            Name: !Sub ${ProjectName}-${Environment}-private-subnet-1

    PrivateSubnet2:
        Description: Private Subnet 2
        Value: !Ref PrivateSubnet2
        Export:
            Name: !Sub ${ProjectName}-${Environment}-private-subnet-2

    ClusterName:
        Description: ECS Cluster Name
        Value: !Ref ECSCluster
        Export:
            Name: !Sub ${ProjectName}-${Environment}-cluster-name

    NamespaceId:
        Description: Service Discovery Namespace ID
        Value: !GetAtt PrivateNamespace.Id
        Export:
            Name: !Sub ${ProjectName}-${Environment}-namespace-id

    BackendSecurityGroupId:
        Description: Backend Security Group ID
        Value: !Ref BackendSecurityGroup
        Export:
            Name: !Sub ${ProjectName}-${Environment}-backend-sg-id

    DatabaseSecurityGroupId:
        Description: Database Security Group ID
        Value: !Ref DatabaseSecurityGroup
        Export:
            Name: !Sub ${ProjectName}-${Environment}-database-sg-id

    CacheSecurityGroupId:
        Description: Cache Security Group ID
        Value: !Ref CacheSecurityGroup
        Export:
            Name: !Sub ${ProjectName}-${Environment}-cache-sg-id
